[template]
src = "default.conf.tmpl"
dest = "/home/nginx/default.conf"
owner = "nginx"
mode = "0644"
keys = [
  "/allow/origin",
  "/api/hostname",
  "/api/port",
  "/port",
]
check_cmd = "/usr/local/openresty/bin/openresty -t"
